services:
  next-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - "POSTGRES_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/mydb?schema=public&connection_limit=10"
      - "REDIS_URL=redis://redis:6379"
      - "ROOT_USERNAME=${ROOT_USERNAME}"
      - "ROOT_PASSWORD=${ROOT_PASSWORD}"
      - "JWT_SECRET=${JWT_SECRET}"
      - "JWT_EXPIRY=604800"
      - "DEMO_MODE=0"
      - "PORT=3000"
      - "API_PORT=3001"
      - "CATCH_ALL_REDIRECT_URL=https://${API_DOMAIN}/public/catch-all-url.html"
    expose:
      - "3000"
    depends_on:
      - postgres
      - redis
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evoclick-app.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.evoclick-app.entrypoints=websecure"
      - "traefik.http.routers.evoclick-app.tls.certResolver=letsencrypt"
      - "traefik.http.services.evoclick-app.loadbalancer.server.port=3000"
    #command: sh -c "npx prisma db push && npm start"

  api:
    build:
      context: ./
      dockerfile: ./Dockerfile.api
    environment:
      - "POSTGRES_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/mydb?schema=public&connection_limit=10"
      - "REDIS_URL=redis://redis:6379"
      - "ROOT_USERNAME=${ROOT_USERNAME}"
      - "ROOT_PASSWORD=${ROOT_PASSWORD}"
      - "JWT_SECRET=${JWT_SECRET}"
      - "JWT_EXPIRY=604800"
      - "DEMO_MODE=0"
      - "PORT=3000"
      - "API_PORT=3001"
      - "CATCH_ALL_REDIRECT_URL=https://${API_DOMAIN}/public/catch-all-url.html"
    expose:
      - "3001"
    depends_on:
      - postgres
      - redis
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evoclick-api.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.evoclick-api.entrypoints=websecure"
      - "traefik.http.routers.evoclick-api.tls.certResolver=letsencrypt"
      - "traefik.http.services.evoclick-api.loadbalancer.server.port=3001"
    #command: sh -c "npx prisma db push && ./bin"

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=mydb
    volumes:
      - ../files/postgres:/var/lib/postgresql/data
    networks:
      - dokploy-network

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - ../files/redis:/data
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
